name: sangria
description: "custom lints wanted for personal developments."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: 7.3.0
  analyzer_plugin: 0.13.0
  custom_lint_builder: 0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
