name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: offich/flutter-fvm-dart-sdk-action@v1
        id: flutter-fvm-dart-sdk-version

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ steps.flutter-fvm-dart-sdk-version.outputs.dart-version }}

      - uses: kuhnroyal/flutter-fvm-config-action@v3
        id: fvm-config-action

      - uses: subosito/flutter-action@v2.18.0
        with:
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}

      - name: install dependencies
        run: flutter pub get

      - name: Publish
        run: dart pub publish --force
